// js/data_dairy.js
// 유제품 세분화: cheese(치즈), butter(버터/크림), yogurt(요거트/간식)

const dairyData = [
    // --- BUTTER & CREAM ---
    { id: 10001, name: '이즈니 AOP 버터 롤 (가염)', brand: 'Isigny Ste-Mère', category: 'butter', spec: '250g', image: 'images/logos/isigny.png', tag: 'AOP' },
    { id: 10002, name: '이즈니 AOP 버터 롤 (무염)', brand: 'Isigny Ste-Mère', category: 'butter', spec: '250g', image: 'images/logos/isigny.png', tag: 'AOP' },
    { id: 10003, name: '이즈니 포션 버터 (컵)', brand: 'Isigny Ste-Mère', category: 'butter', spec: '10g x 60ea', image: 'images/logos/isigny.png', tag: '호텔납품' },
    { id: 10004, name: '이즈니 생메르 크렘 프레쉬 AOP', brand: 'Isigny Ste-Mère', category: 'butter', spec: '200ml', image: 'images/logos/isigny.png', tag: '소스용' },
    { id: 10008, name: '이즈니 AOP 버터 브릭', brand: 'Isigny Ste-Mère', category: 'butter', spec: '250g', image: 'images/logos/isigny.png', tag: 'AOP' },
    { id: 10009, name: '이즈니 오가닉 버터 브릭', brand: 'Isigny Ste-Mère', category: 'butter', spec: '200g', image: 'images/logos/isigny.png', tag: '유기농' },
    { id: 10010, name: '이즈니 냉동 버터 벌크', brand: 'Isigny Ste-Mère', category: 'butter', spec: '10kg', image: 'images/logos/isigny.png', tag: '대용량' },
    { id: 10024, name: '엠보그 휘핑크림', brand: 'Emborg', category: 'butter', spec: '1L', image: 'https://via.placeholder.com/150?text=Emborg', tag: '제과용' },
    { id: 10025, name: '엠보그 사우어 크림', brand: 'Emborg', category: 'butter', spec: '1L', image: 'https://via.placeholder.com/150?text=Emborg', tag: '업소용' },
    { id: 10026, name: '오가닉밸리 유기농 기 버터', brand: 'Organic Valley', category: 'butter', spec: '212g', image: 'https://via.placeholder.com/150?text=Organic+Valley', tag: '유기농' },
    { id: 10036, name: '올덴버거 휘핑크림', brand: 'Oldenburger', category: 'butter', spec: '1L', image: 'https://via.placeholder.com/150?text=Oldenburger', tag: '가성비' },
    { id: 10054, name: '브라잘레 알프스 버터 포션', brand: 'Brazzale', category: 'butter', spec: '10g', image: 'https://via.placeholder.com/150?text=Brazzale', tag: '호텔납품' },
    { id: 10062, name: '엘르&비르 고메 버터 (무염)', brand: 'Elle & Vire', category: 'butter', spec: '200g', image: 'https://via.placeholder.com/150?text=Elle', tag: '프랑스' },

    // --- CHEESE (FRESH, SOFT, HARD, BLUE) ---
    { id: 10005, name: '이즈니 브리 치즈', brand: 'Isigny Ste-Mère', category: 'cheese', spec: '1kg', image: 'images/logos/isigny.png', tag: '업소용' },
    { id: 10006, name: '이즈니 까망베르 노르망디', brand: 'Isigny Ste-Mère', category: 'cheese', spec: '250g', image: 'images/logos/isigny.png', tag: 'AOP' },
    { id: 10007, name: '이즈니 미몰레뜨 (6개월)', brand: 'Isigny Ste-Mère', category: 'cheese', spec: '210g', image: 'images/logos/isigny.png', tag: '숙성치즈' },
    { id: 10011, name: '벨지오 모짜렐라 로그 슬라이스', brand: 'BelGioioso', category: 'cheese', spec: '907g', image: 'images/logos/belgioioso.png', tag: '카프레제' },
    { id: 10012, name: '벨지오 부라타 (4 balls)', brand: 'BelGioioso', category: 'cheese', spec: '226g', image: 'images/logos/belgioioso.png', tag: 'BEST' },
    { id: 10013, name: '벨지오 마스카포네', brand: 'BelGioioso', category: 'cheese', spec: '226g', image: 'images/logos/belgioioso.png', tag: '티라미수' },
    { id: 10014, name: '벨지오 리코타 미니 컵', brand: 'BelGioioso', category: 'cheese', spec: '142g', image: 'images/logos/belgioioso.png', tag: '미니' },
    { id: 10015, name: '벨지오 스트라치아렐라', brand: 'BelGioioso', category: 'cheese', spec: '226g', image: 'images/logos/belgioioso.png', tag: '부라타속' },
    { id: 10016, name: '벨지오 파마산 쉐이브드 컵', brand: 'BelGioioso', category: 'cheese', spec: '113g', image: 'images/logos/belgioioso.png', tag: '토핑용' },
    { id: 10017, name: '암브로시 마스카포네', brand: 'Ambrosi', category: 'cheese', spec: '500g', image: 'images/logos/ambrosi.png', tag: '이탈리아' },
    { id: 10018, name: '암브로시 고르곤졸라 피칸테', brand: 'Ambrosi', category: 'cheese', spec: '150g', image: 'images/logos/ambrosi.png', tag: '블루치즈' },
    { id: 10019, name: '암브로시 그라나 파다노', brand: 'Ambrosi', category: 'cheese', spec: '1kg', image: 'images/logos/ambrosi.png', tag: '경성치즈' },
    { id: 10020, name: '암브로시 파르미지아노 레지아노', brand: 'Ambrosi', category: 'cheese', spec: '150g', image: 'images/logos/ambrosi.png', tag: 'DOP' },
    { id: 10021, name: '엠보그 모짜렐라 슬라이스', brand: 'Emborg', category: 'cheese', spec: '150g', image: 'https://via.placeholder.com/150?text=Emborg', tag: '슬라이스' },
    { id: 10022, name: '엠보그 에멘탈 슬라이스', brand: 'Emborg', category: 'cheese', spec: '150g', image: 'https://via.placeholder.com/150?text=Emmental', tag: '슬라이스' },
    { id: 10023, name: '엠보그 크림치즈', brand: 'Emborg', category: 'cheese', spec: '1.36kg', image: 'https://via.placeholder.com/150?text=Cream+Cheese', tag: '대용량' },
    { id: 10027, name: '오가닉밸리 유기농 스트링 치즈', brand: 'Organic Valley', category: 'cheese', spec: '170g', image: 'https://via.placeholder.com/150?text=String+Cheese', tag: '키즈' },
    { id: 10028, name: '오가닉밸리 유기농 크림치즈', brand: 'Organic Valley', category: 'cheese', spec: '226g', image: 'https://via.placeholder.com/150?text=Org+Cream+Cheese', tag: '유기농' },
    { id: 10029, name: '퍼시픽 콜비잭 치즈', brand: 'Pacific Cheese', category: 'cheese', spec: '227g', image: 'https://via.placeholder.com/150?text=Pacific', tag: '미국' },
    { id: 10030, name: '퍼시픽 마일드 체다 치즈', brand: 'Pacific Cheese', category: 'cheese', spec: '227g', image: 'https://via.placeholder.com/150?text=Mild+Cheddar', tag: '미국' },
    { id: 10031, name: '퍼시픽 몬테레이 잭', brand: 'Pacific Cheese', category: 'cheese', spec: '226g', image: 'https://via.placeholder.com/150?text=Monterey+Jack', tag: '미국' },
    { id: 10032, name: '조트 바이에른탈러 에멘탈', brand: 'Zott', category: 'cheese', spec: '200g', image: 'https://via.placeholder.com/150?text=Zott', tag: '독일' },
    { id: 10033, name: '조트 모짜렐라 슬라이스', brand: 'Zott', category: 'cheese', spec: '200g', image: 'https://via.placeholder.com/150?text=Zott', tag: '슬라이스' },
    { id: 10034, name: '조트 타이거 스트링 치즈', brand: 'Zott', category: 'cheese', spec: '84g', image: 'https://via.placeholder.com/150?text=Tiger+String', tag: '키즈' },
    { id: 10037, name: '그랑도르 고다 미니', brand: 'Grand\'Or', category: 'cheese', spec: '100g', image: 'https://via.placeholder.com/150?text=Mini+Gouda', tag: '스낵' },
    { id: 10038, name: '그랑도르 스모크 치즈', brand: 'Grand\'Or', category: 'cheese', spec: '200g', image: 'https://via.placeholder.com/150?text=Smoked', tag: '안주' },
    { id: 10039, name: '그랑도르 에담 슬라이스', brand: 'Grand\'Or', category: 'cheese', spec: '160g', image: 'https://via.placeholder.com/150?text=Edam+Slice', tag: '슬라이스' },
    { id: 10040, name: '브리미 모짜렐라 블록', brand: 'Brimi', category: 'cheese', spec: '1kg', image: 'https://via.placeholder.com/150?text=Brimi', tag: '피자용' },
    { id: 10041, name: '브리미 리코타', brand: 'Brimi', category: 'cheese', spec: '250g', image: 'https://via.placeholder.com/150?text=Brimi', tag: '프레쉬' },
    { id: 10042, name: '브리미 모짜렐라 락토스 프리', brand: 'Brimi', category: 'cheese', spec: '125g', image: 'https://via.placeholder.com/150?text=Lactose+Free', tag: '락토프리' },
    { id: 10049, name: '달몰리스 냉동 부라타', brand: 'Dal Molise', category: 'cheese', spec: '125g', image: 'https://via.placeholder.com/150?text=Frozen+Burrata', tag: '냉동' },
    { id: 10050, name: '달몰리스 냉동 모짜렐라', brand: 'Dal Molise', category: 'cheese', spec: '125g', image: 'https://via.placeholder.com/150?text=Frozen+Mozz', tag: '냉동' },
    { id: 10051, name: '달몰리스 냉동 트러플 부라타', brand: 'Dal Molise', category: 'cheese', spec: '125g', image: 'https://via.placeholder.com/150?text=Truffle+Burrata', tag: '트러플' },
    { id: 10052, name: '쁘띠구르망 그라나파다노 눈꽃 슈레드', brand: 'Petit Gourmand', category: 'cheese', spec: '200g', image: 'https://via.placeholder.com/150?text=Shred', tag: '토핑용' },
    { id: 10053, name: '쁘띠구르망 4프로마쥬 슈레드 치즈', brand: 'Petit Gourmand', category: 'cheese', spec: '800g', image: 'https://via.placeholder.com/150?text=4Cheese+Shred', tag: '피자용' },
    { id: 10055, name: '에푸아스', brand: 'Germain', category: 'cheese', spec: '250g', image: 'https://via.placeholder.com/150?text=Germain', tag: '워시치즈' },
    { id: 10056, name: '랑그르', brand: 'Germain', category: 'cheese', spec: '180g', image: 'https://via.placeholder.com/150?text=Langres', tag: '워시치즈' },
    { id: 10057, name: '이즈니 브리 60%', brand: 'Isigny Ste-Mère', category: 'cheese', spec: '1kg', image: 'images/logos/isigny.png', tag: '더블크림' },
    { id: 10058, name: '이즈니 트러플 까망베르', brand: 'Isigny Ste-Mère', category: 'cheese', spec: '150g', image: 'images/logos/isigny.png', tag: '트러플' },
    { id: 10059, name: '일드 프랑스 미니 브리', brand: 'Ile De France', category: 'cheese', spec: '125g', image: 'https://via.placeholder.com/150?text=IDF', tag: '스낵' },
    { id: 10060, name: '생 앙드레', brand: 'Savencia', category: 'cheese', spec: '200g', image: 'https://via.placeholder.com/150?text=Saint+Andre', tag: '트리플크림' },
    { id: 10061, name: '생 아구르 크림', brand: 'Savencia', category: 'cheese', spec: '150g', image: 'https://via.placeholder.com/150?text=Saint+Agur', tag: '블루크림' },
    { id: 10063, name: '르 갈 크림치즈', brand: 'Le Gall', category: 'cheese', spec: '1kg', image: 'https://via.placeholder.com/150?text=Le+Gall', tag: '대용량' },
    { id: 10064, name: '알미토 페타치즈 허브', brand: 'Almito', category: 'cheese', spec: '280g', image: 'https://via.placeholder.com/150?text=Almito', tag: '오일절임' },
    { id: 10065, name: '알미토 체리페퍼 크림치즈', brand: 'Almito', category: 'cheese', spec: '280g', image: 'https://via.placeholder.com/150?text=Almito', tag: '안주' },

    // --- YOGURT ---
    { id: 10035, name: '올덴버거 멸균 우유', brand: 'Oldenburger', category: 'yogurt', spec: '1L', image: 'https://via.placeholder.com/150?text=Oldenburger', tag: '멸균' },
    { id: 10043, name: '파예 클래식 그릭 요거트', brand: 'Fage', category: 'yogurt', spec: '450g', image: 'https://via.placeholder.com/150?text=Fage', tag: '꾸덕함' },
    { id: 10044, name: '파예 무지방 그릭 요거트', brand: 'Fage', category: 'yogurt', spec: '170g', image: 'https://via.placeholder.com/150?text=Fage+0', tag: '다이어트' },
    { id: 10045, name: '파예 그릭 요거트 (허니)', brand: 'Fage', category: 'yogurt', spec: '170g', image: 'https://via.placeholder.com/150?text=Fage+Honey', tag: '디저트' },
    { id: 10046, name: '크리크리 그릭 프로즌 요거트', brand: 'Kri Kri', category: 'yogurt', spec: '320g', image: 'https://via.placeholder.com/150?text=KriKri', tag: '아이스크림' },
    { id: 10047, name: '티에스씨 오레오 밀크 스낵', brand: 'TSC', category: 'yogurt', spec: '30g', image: 'images/logos/tsc.png', tag: '냉장디저트' },
    { id: 10048, name: '티에스씨 밀카 밀크 스낵', brand: 'TSC', category: 'yogurt', spec: '32g', image: 'https://via.placeholder.com/150?text=Milka+Snack', tag: '냉장디저트' },
];